serv:
  - iam
  - devportal
  - wharf
  - broker
  - backplane
  - mobile
  - frontier
  - libs
  - bridge
ds:
  - optiml
  - pyper
sport:
  - node
  - router
  - netnet
  - pnp
  - logger
  - pcb
  - sensors
